services:
  api-hrms:
    platform: linux/amd64
    build:
      context: ../../
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      POSTGRES_DB_HOST: db
      POSTGRES_DB_PORT: 5432
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      REDIS_CONNECTION_STRING: redis:6379
    ports:
      - "5004:5000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-net

networks:
  app-net: