// <auto-generated />
using System;
using ApiHrm.Infrastructures.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace api_hrm.Migrations
{
    [DbContext(typeof(hrmAppDbContext))]
    [Migration("20260609125947_Phase1ProductionUpdates")]
    partial class Phase1ProductionUpdates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApiHrm.Domains.Entities.Applicant", b =>
                {
                    b.Property<int>("Applicant_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Applicant_ID"));

                    b.Property<DateTime>("Application_Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Contact_Details")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Payment_Method")
                        .HasColumnType("text");

                    b.Property<string>("Resume_URL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Applicant_ID");

                    b.ToTable("r_Apllicant_Records", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.AttendanceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("attendance_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Employee_Id")
                        .HasColumnType("integer");

                    b.Property<bool>("Is_Manual_Override")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("Log_Date")
                        .HasColumnType("date");

                    b.Property<string>("Log_Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("Time_In")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Time_Out")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Employee_Id");

                    b.ToTable("r_Attendance_Log", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("audit_log_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ip_Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Record_Id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Record_Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("User_Id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("User_Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("r_Audit_Log", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.BonusIncentive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("bonus_incentive_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Bonus_Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Employee_Id")
                        .HasColumnType("integer");

                    b.Property<decimal>("Incentive_Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Payroll_Run_Id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Employee_Id");

                    b.HasIndex("Payroll_Run_Id");

                    b.ToTable("r_Bonus_Incentive", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.CashAdvance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cash_advance_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount_Requested")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Employee_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Employee_Id");

                    b.ToTable("r_Cash_Advance", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.Checklist", b =>
                {
                    b.Property<int>("Checklist_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Checklist_ID"));

                    b.Property<int>("Applicant_ID")
                        .HasColumnType("integer");

                    b.Property<bool>("Has_Medical")
                        .HasColumnType("boolean");

                    b.Property<bool>("Has_NBI")
                        .HasColumnType("boolean");

                    b.Property<bool>("Has_Xray")
                        .HasColumnType("boolean");

                    b.Property<bool>("has_PAGIBIG")
                        .HasColumnType("boolean");

                    b.Property<bool>("has_PhilHealth")
                        .HasColumnType("boolean");

                    b.Property<bool>("has_SSS")
                        .HasColumnType("boolean");

                    b.Property<bool>("has_TIN")
                        .HasColumnType("boolean");

                    b.HasKey("Checklist_ID");

                    b.HasIndex("Applicant_ID");

                    b.ToTable("r_Checklist", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.Document", b =>
                {
                    b.Property<int>("Document_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Document_ID"));

                    b.Property<int?>("Applicant_ID")
                        .HasColumnType("integer");

                    b.Property<string>("Doc_Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Employee_ID")
                        .HasColumnType("integer");

                    b.Property<string>("file_URL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("upload_date")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Document_ID");

                    b.HasIndex("Applicant_ID");

                    b.HasIndex("Employee_ID");

                    b.ToTable("r_Document", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.Employee", b =>
                {
                    b.Property<int>("Employee_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Employee_Id"));

                    b.Property<string>("AccountNumber")
                        .HasColumnType("text");

                    b.Property<string>("Contact_Details")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("Hire_Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role_ID")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Employee_Id");

                    b.HasIndex("Role_ID");

                    b.ToTable("r_Employee_Record", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.EmployeeDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("employee_document_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Document_Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Employee_Id")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Expiry_Date")
                        .HasColumnType("date");

                    b.Property<string>("File_Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Issue_Date")
                        .HasColumnType("date");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("VerifiedByUserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Employee_Id");

                    b.ToTable("r_Employee_Document", "public", t =>
                        {
                            t.HasCheckConstraint("CK_Employee_Document_Expiry_After_Issue", "\"Expiry_Date\" > \"Issue_Date\"");
                        });
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.EmployeeHistory", b =>
                {
                    b.Property<int>("History_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("History_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("History_ID"));

                    b.Property<string>("Action_Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Action_Type");

                    b.Property<DateTime>("Changed_At")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("Changed_At");

                    b.Property<string>("Changed_By")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Changed_By");

                    b.Property<int>("Employee_ID")
                        .HasColumnType("integer")
                        .HasColumnName("Employee_ID");

                    b.Property<string>("New_Value")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("New_Value");

                    b.Property<string>("Old_Value")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Old_Value");

                    b.HasKey("History_ID");

                    b.HasIndex("Employee_ID");

                    b.ToTable("r_Employee_History", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.EmployeePayrollRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("payroll_record_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Basic_Pay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Employee_Id")
                        .HasColumnType("integer");

                    b.Property<decimal>("Net_Pay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OT_Pay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PagIbig_Deduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Payroll_Run_Id")
                        .HasColumnType("integer");

                    b.Property<decimal>("PhilHealth_Deduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Sss_Deduction")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Employee_Id");

                    b.HasIndex("Payroll_Run_Id");

                    b.ToTable("r_Employee_Payroll_Record", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.EmployeeShift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("shift_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Effective_Date")
                        .HasColumnType("date");

                    b.Property<int>("Employee_Id")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("End_Date")
                        .HasColumnType("date");

                    b.Property<string>("Shift_Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Employee_Id");

                    b.ToTable("r_Employee_Shift", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.Exit", b =>
                {
                    b.Property<int>("Exit_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Exit_ID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Employee_ID")
                        .HasColumnType("integer");

                    b.Property<string>("Interview_Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Interviewed_By")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason_For_Leaving")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Exit_ID");

                    b.HasIndex("Employee_ID");

                    b.ToTable("r_Exit_Interviews", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.LeaveBalance", b =>
                {
                    b.Property<int>("Balance_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Balance_ID"));

                    b.Property<int>("Allocated_Days")
                        .HasColumnType("integer");

                    b.Property<int>("Employee_ID")
                        .HasColumnType("integer");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("Pending_Days")
                        .HasColumnType("integer");

                    b.Property<int>("Used_Days")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Balance_ID");

                    b.HasIndex("Employee_ID");

                    b.HasIndex("LeaveTypeId");

                    b.ToTable("r_Leave_Balance", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.LeaveRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("leave_request_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Employee_Id")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("End_Date")
                        .HasColumnType("date");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Start_Date")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Employee_Id");

                    b.HasIndex("LeaveTypeId");

                    b.ToTable("r_Leave_Request", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.LeaveType", b =>
                {
                    b.Property<int>("LeaveTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LeaveTypeId"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("LeaveTypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LeaveTypeId");

                    b.ToTable("r_Leave_Type", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.MissingLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("missing_log_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Employee_Id")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Log_Date")
                        .HasColumnType("date");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Employee_Id");

                    b.ToTable("r_Missing_Log", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.PayrollRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("payroll_run_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("CutOff_End_Date")
                        .HasColumnType("date");

                    b.Property<DateOnly>("CutOff_Start_Date")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("r_Payroll_Run", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.Payslip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("payslip_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Employee_Id")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Payout_Date")
                        .HasColumnType("date");

                    b.Property<int>("Payroll_Run_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Pdf_Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Employee_Id");

                    b.HasIndex("Payroll_Run_Id");

                    b.ToTable("r_Payslip", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.Role", b =>
                {
                    b.Property<int>("Role_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Role_ID"));

                    b.Property<string>("Role_Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Role_ID");

                    b.ToTable("r_Role", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.AttendanceLog", b =>
                {
                    b.HasOne("ApiHrm.Domains.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("Employee_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.BonusIncentive", b =>
                {
                    b.HasOne("ApiHrm.Domains.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("Employee_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiHrm.Domains.Entities.PayrollRun", "PayrollRun")
                        .WithMany("BonusIncentives")
                        .HasForeignKey("Payroll_Run_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("PayrollRun");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.CashAdvance", b =>
                {
                    b.HasOne("ApiHrm.Domains.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("Employee_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.Checklist", b =>
                {
                    b.HasOne("ApiHrm.Domains.Entities.Applicant", "Applicant")
                        .WithMany("Checklists")
                        .HasForeignKey("Applicant_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.Document", b =>
                {
                    b.HasOne("ApiHrm.Domains.Entities.Applicant", "applicant")
                        .WithMany("Documents")
                        .HasForeignKey("Applicant_ID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ApiHrm.Domains.Entities.Employee", "employee")
                        .WithMany("Documents")
                        .HasForeignKey("Employee_ID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("applicant");

                    b.Navigation("employee");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.Employee", b =>
                {
                    b.HasOne("ApiHrm.Domains.Entities.Role", "role")
                        .WithMany("Employees")
                        .HasForeignKey("Role_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("role");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.EmployeeDocument", b =>
                {
                    b.HasOne("ApiHrm.Domains.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("Employee_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.EmployeeHistory", b =>
                {
                    b.HasOne("ApiHrm.Domains.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("Employee_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.EmployeePayrollRecord", b =>
                {
                    b.HasOne("ApiHrm.Domains.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("Employee_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiHrm.Domains.Entities.PayrollRun", "PayrollRun")
                        .WithMany("EmployeePayrollRecords")
                        .HasForeignKey("Payroll_Run_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("PayrollRun");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.EmployeeShift", b =>
                {
                    b.HasOne("ApiHrm.Domains.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("Employee_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.Exit", b =>
                {
                    b.HasOne("ApiHrm.Domains.Entities.Employee", "Employee")
                        .WithMany("Exits")
                        .HasForeignKey("Employee_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.LeaveBalance", b =>
                {
                    b.HasOne("ApiHrm.Domains.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("Employee_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiHrm.Domains.Entities.LeaveType", "LeaveType")
                        .WithMany("LeaveBalances")
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.LeaveRequest", b =>
                {
                    b.HasOne("ApiHrm.Domains.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("Employee_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiHrm.Domains.Entities.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.MissingLog", b =>
                {
                    b.HasOne("ApiHrm.Domains.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("Employee_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.Payslip", b =>
                {
                    b.HasOne("ApiHrm.Domains.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("Employee_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiHrm.Domains.Entities.PayrollRun", "PayrollRun")
                        .WithMany("Payslips")
                        .HasForeignKey("Payroll_Run_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("PayrollRun");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.Applicant", b =>
                {
                    b.Navigation("Checklists");

                    b.Navigation("Documents");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.Employee", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Exits");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.LeaveType", b =>
                {
                    b.Navigation("LeaveBalances");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.PayrollRun", b =>
                {
                    b.Navigation("BonusIncentives");

                    b.Navigation("EmployeePayrollRecords");

                    b.Navigation("Payslips");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.Role", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
