// <auto-generated />
using System;
using ApiHrm.Infrastructures.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace api_hrm.Migrations
{
    [DbContext(typeof(hrmAppDbContext))]
    [Migration("20260619073152_MakeInterviewDateNullable")]
    partial class MakeInterviewDateNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApiHrm.Domains.Entities.Applicant", b =>
                {
                    b.Property<int>("Applicant_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Applicant_ID"));

                    b.Property<DateOnly>("Application_Date")
                        .HasColumnType("date");

                    b.Property<string>("Contact_Details")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("Expected_Start_Date")
                        .HasColumnType("date");

                    b.Property<string>("First_Name")
                        .HasColumnType("text");

                    b.Property<string>("Hiring_Stage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("Interview_Date")
                        .HasColumnType("date");

                    b.Property<string>("Last_Name")
                        .HasColumnType("text");

                    b.Property<bool>("Medical_Document_Completed")
                        .HasColumnType("boolean");

                    b.Property<bool>("NBI_Document_Completed")
                        .HasColumnType("boolean");

                    b.Property<string>("Payment_Method")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .HasColumnType("text");

                    b.Property<string>("Resume_URL")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("XRay_Document_Completed")
                        .HasColumnType("boolean");

                    b.HasKey("Applicant_ID");

                    b.ToTable("r_Apllicant_Records", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.AttendanceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("attendance_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Employee_Id")
                        .HasColumnType("integer");

                    b.Property<bool>("Is_Manual_Override")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("Log_Date")
                        .HasColumnType("date");

                    b.Property<string>("Log_Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("Time_In")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Time_Out")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Employee_Id");

                    b.ToTable("r_Attendance_Log", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("audit_log_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ip_Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Record_Id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Record_Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("User_Id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("User_Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("r_Audit_Log", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.BonusIncentive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("bonus_incentive_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Bonus_Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Employee_Id")
                        .HasColumnType("integer");

                    b.Property<decimal>("Incentive_Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Payroll_Run_Id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Employee_Id");

                    b.HasIndex("Payroll_Run_Id");

                    b.ToTable("r_Bonus_Incentive", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.CashAdvance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cash_advance_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount_Requested")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Employee_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Employee_Id");

                    b.ToTable("r_Cash_Advance", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.Checklist", b =>
                {
                    b.Property<int>("Checklist_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Checklist_ID"));

                    b.Property<int>("Applicant_ID")
                        .HasColumnType("integer");

                    b.Property<bool>("Has_Medical")
                        .HasColumnType("boolean");

                    b.Property<bool>("Has_NBI")
                        .HasColumnType("boolean");

                    b.Property<bool>("Has_Xray")
                        .HasColumnType("boolean");

                    b.Property<bool>("has_PAGIBIG")
                        .HasColumnType("boolean");

                    b.Property<bool>("has_PhilHealth")
                        .HasColumnType("boolean");

                    b.Property<bool>("has_SSS")
                        .HasColumnType("boolean");

                    b.Property<bool>("has_TIN")
                        .HasColumnType("boolean");

                    b.HasKey("Checklist_ID");

                    b.HasIndex("Applicant_ID");

                    b.ToTable("r_Checklist", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.CompanyProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Employee_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Employee_Id_Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Equipment_JSON")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Id_Issue_Date")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("Return_Date")
                        .HasColumnType("date");

                    b.Property<string>("Uniform_Bottom_Size")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateOnly>("Uniform_Issue_Date")
                        .HasColumnType("date");

                    b.Property<string>("Uniform_Shoe_Size")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Uniform_Top_Size")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("Employee_Id")
                        .IsUnique();

                    b.ToTable("r_Company_Property", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.ContactInformation", b =>
                {
                    b.Property<int>("ContactInformationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ContactInformationId"));

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<string>("PermanentAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PresentAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TelephoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("ContactInformationId");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("r_Contact_Information", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.Document", b =>
                {
                    b.Property<int>("Document_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Document_ID"));

                    b.Property<int?>("Applicant_ID")
                        .HasColumnType("integer");

                    b.Property<string>("Doc_Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Employee_ID")
                        .HasColumnType("integer");

                    b.Property<string>("file_URL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("upload_date")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Document_ID");

                    b.HasIndex("Applicant_ID");

                    b.HasIndex("Employee_ID");

                    b.ToTable("r_Document", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.DocumentStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Document_Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Employee_Id")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("Expiry_Date")
                        .HasColumnType("date");

                    b.Property<bool>("Is_Completed")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("Last_Updated")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("Employee_Id");

                    b.ToTable("r_Document_Status", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.EmailDispatchLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("email_dispatch_log_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EmployeeEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("PayslipId")
                        .HasColumnType("integer");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("PayslipId");

                    b.ToTable("r_Email_Dispatch_Log", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.EmergencyContact", b =>
                {
                    b.Property<int>("EmergencyContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmergencyContactId"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("EmergencyContactId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("r_Emergency_Contact", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmployeeId"));

                    b.Property<int>("AvatarIndex")
                        .HasColumnType("integer");

                    b.Property<string>("BloodType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CivilStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("ErpUserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Role_ID")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EmployeeId");

                    b.HasIndex("Role_ID");

                    b.ToTable("r_Employee_Record", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.EmployeeDocument", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DocumentId"));

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Expiry_Date")
                        .HasColumnType("date");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateOnly>("Issue_Date")
                        .HasColumnType("date");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("VerifiedByUserId")
                        .HasColumnType("integer");

                    b.HasKey("DocumentId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("r_Employee_Document", "public", t =>
                        {
                            t.HasCheckConstraint("CK_Employee_Document_Expiry_After_Issue", "\"Expiry_Date\" > \"Issue_Date\"");
                        });
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.EmployeeHistory", b =>
                {
                    b.Property<int>("History_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("History_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("History_ID"));

                    b.Property<string>("Action_Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Action_Type");

                    b.Property<DateTime>("Changed_At")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("Changed_At");

                    b.Property<string>("Changed_By")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Changed_By");

                    b.Property<int>("Employee_ID")
                        .HasColumnType("integer")
                        .HasColumnName("Employee_ID");

                    b.Property<string>("New_Value")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("New_Value");

                    b.Property<string>("Old_Value")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Old_Value");

                    b.HasKey("History_ID");

                    b.HasIndex("Employee_ID");

                    b.ToTable("r_Employee_History", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.EmployeePayrollRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("payroll_record_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Basic_Pay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Days_Worked")
                        .HasColumnType("integer");

                    b.Property<int>("Employee_Id")
                        .HasColumnType("integer");

                    b.Property<decimal>("Net_Pay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OT_Hours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OT_Pay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PagIbig_Deduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Payroll_Run_Id")
                        .HasColumnType("integer");

                    b.Property<decimal>("PhilHealth_Deduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Sss_Deduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Tax_Deduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total_Deductions")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Employee_Id");

                    b.HasIndex("Payroll_Run_Id");

                    b.ToTable("r_Employee_Payroll_Record", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.EmployeeShift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("shift_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Effective_Date")
                        .HasColumnType("date");

                    b.Property<int>("Employee_Id")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("End_Date")
                        .HasColumnType("date");

                    b.Property<string>("Shift_Code")
                        .IsRequired()
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Employee_Id");

                    b.HasIndex("Shift_Code");

                    b.ToTable("r_Employee_Shift", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.EmploymentDetails", b =>
                {
                    b.Property<int>("EmploymentDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmploymentDetailsId"));

                    b.Property<decimal>("BasePay")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<string>("EmploymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SalaryGrade")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Tenure")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("EmploymentDetailsId");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("r_Employment_Details", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.Exit", b =>
                {
                    b.Property<int>("Exit_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Exit_ID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Employee_ID")
                        .HasColumnType("integer");

                    b.Property<string>("Interview_Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Interviewed_By")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason_For_Leaving")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Exit_ID");

                    b.HasIndex("Employee_ID");

                    b.ToTable("r_Exit_Interviews", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.GovernmentId", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Employee_Id")
                        .HasColumnType("integer");

                    b.Property<string>("HDMF_Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PhilHealth_Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SSS_Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TIN_Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Employee_Id")
                        .IsUnique();

                    b.ToTable("r_Government_Id", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.LeaveBalance", b =>
                {
                    b.Property<int>("Balance_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Balance_ID"));

                    b.Property<int>("Allocated_Days")
                        .HasColumnType("integer");

                    b.Property<int>("Employee_ID")
                        .HasColumnType("integer");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("Pending_Days")
                        .HasColumnType("integer");

                    b.Property<int>("Used_Days")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Balance_ID");

                    b.HasIndex("Employee_ID");

                    b.HasIndex("LeaveTypeId");

                    b.ToTable("r_Leave_Balance", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.LeaveRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("leave_request_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Employee_Id")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("End_Date")
                        .HasColumnType("date");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Start_Date")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Employee_Id");

                    b.HasIndex("LeaveTypeId");

                    b.ToTable("r_Leave_Request", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.LeaveType", b =>
                {
                    b.Property<int>("LeaveTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LeaveTypeId"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("LeaveTypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LeaveTypeId");

                    b.ToTable("r_Leave_Type", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.MissingLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("missing_log_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Employee_Id")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Log_Date")
                        .HasColumnType("date");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Employee_Id");

                    b.ToTable("r_Missing_Log", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.PagIbigBracket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pagibig_bracket_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EffectiveYear")
                        .HasColumnType("integer");

                    b.Property<decimal>("EmployeeShareRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EmployerShareRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MonthlyContribution")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalaryRangeEnd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalaryRangeStart")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("r_PagIbig_Bracket", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.PayoutSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("payout_summary_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeCount")
                        .HasColumnType("integer");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("PayrollRunId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PayrollRunId");

                    b.ToTable("r_Payout_Summary", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.PayrollRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("payroll_run_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchReferenceNumber")
                        .HasColumnType("text");

                    b.Property<DateOnly>("CutOff_End_Date")
                        .HasColumnType("date");

                    b.Property<DateOnly>("CutOff_Start_Date")
                        .HasColumnType("date");

                    b.Property<DateTime?>("Finalized_At")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("Finalized_By")
                        .HasColumnType("integer");

                    b.Property<string>("Payout_Summary_Json")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("r_Payroll_Run", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.Payslip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("payslip_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Download_Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Email_Retry_Count")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Email_Sent_At")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Employee_Id")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Payout_Date")
                        .HasColumnType("date");

                    b.Property<int>("Payroll_Run_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Pdf_Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Employee_Id");

                    b.HasIndex("Payroll_Run_Id");

                    b.ToTable("r_Payslip", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.PhilHealthBracket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("philhealth_bracket_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EffectiveYear")
                        .HasColumnType("integer");

                    b.Property<decimal>("EmployeeShareRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EmployerShareRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MonthlyContribution")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalaryRangeEnd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalaryRangeStart")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("r_PhilHealth_Bracket", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.Role", b =>
                {
                    b.Property<int>("Role_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Role_ID"));

                    b.Property<string>("Role_Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Role_ID");

                    b.ToTable("r_Role", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.ShiftDefinition", b =>
                {
                    b.Property<string>("ShiftCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<decimal>("StandardHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.HasKey("ShiftCode");

                    b.ToTable("r_Shift_Definition", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.SssBracket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("sss_bracket_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EffectiveYear")
                        .HasColumnType("integer");

                    b.Property<decimal>("EmployeeShareRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EmployerShareRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MonthlyContribution")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalaryRangeEnd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalaryRangeStart")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("r_Sss_Bracket", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.TaxBracket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tax_bracket_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AnnualRangeEnd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AnnualRangeStart")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BaseTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EffectiveYear")
                        .HasColumnType("integer");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("r_Tax_Bracket", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.AttendanceLog", b =>
                {
                    b.HasOne("ApiHrm.Domains.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("Employee_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.BonusIncentive", b =>
                {
                    b.HasOne("ApiHrm.Domains.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("Employee_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiHrm.Domains.Entities.PayrollRun", "PayrollRun")
                        .WithMany("BonusIncentives")
                        .HasForeignKey("Payroll_Run_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("PayrollRun");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.CashAdvance", b =>
                {
                    b.HasOne("ApiHrm.Domains.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("Employee_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.Checklist", b =>
                {
                    b.HasOne("ApiHrm.Domains.Entities.Applicant", "Applicant")
                        .WithMany("Checklists")
                        .HasForeignKey("Applicant_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.CompanyProperty", b =>
                {
                    b.HasOne("ApiHrm.Domains.Entities.Employee", "Employee")
                        .WithOne("CompanyProperty")
                        .HasForeignKey("ApiHrm.Domains.Entities.CompanyProperty", "Employee_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.ContactInformation", b =>
                {
                    b.HasOne("ApiHrm.Domains.Entities.Employee", "Employee")
                        .WithOne("ContactInformation")
                        .HasForeignKey("ApiHrm.Domains.Entities.ContactInformation", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.Document", b =>
                {
                    b.HasOne("ApiHrm.Domains.Entities.Applicant", "applicant")
                        .WithMany("Documents")
                        .HasForeignKey("Applicant_ID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ApiHrm.Domains.Entities.Employee", "employee")
                        .WithMany("Documents")
                        .HasForeignKey("Employee_ID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("applicant");

                    b.Navigation("employee");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.DocumentStatus", b =>
                {
                    b.HasOne("ApiHrm.Domains.Entities.Employee", "Employee")
                        .WithMany("DocumentStatuses")
                        .HasForeignKey("Employee_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.EmailDispatchLog", b =>
                {
                    b.HasOne("ApiHrm.Domains.Entities.Payslip", "Payslip")
                        .WithMany()
                        .HasForeignKey("PayslipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Payslip");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.EmergencyContact", b =>
                {
                    b.HasOne("ApiHrm.Domains.Entities.Employee", "Employee")
                        .WithMany("EmergencyContacts")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.Employee", b =>
                {
                    b.HasOne("ApiHrm.Domains.Entities.Role", "role")
                        .WithMany("Employees")
                        .HasForeignKey("Role_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("role");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.EmployeeDocument", b =>
                {
                    b.HasOne("ApiHrm.Domains.Entities.Employee", "Employee")
                        .WithMany("EmployeeDocuments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.EmployeeHistory", b =>
                {
                    b.HasOne("ApiHrm.Domains.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("Employee_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.EmployeePayrollRecord", b =>
                {
                    b.HasOne("ApiHrm.Domains.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("Employee_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiHrm.Domains.Entities.PayrollRun", "PayrollRun")
                        .WithMany("EmployeePayrollRecords")
                        .HasForeignKey("Payroll_Run_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("PayrollRun");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.EmployeeShift", b =>
                {
                    b.HasOne("ApiHrm.Domains.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("Employee_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiHrm.Domains.Entities.ShiftDefinition", "ShiftDefinition")
                        .WithMany("EmployeeShifts")
                        .HasForeignKey("Shift_Code")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("ShiftDefinition");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.EmploymentDetails", b =>
                {
                    b.HasOne("ApiHrm.Domains.Entities.Employee", "Employee")
                        .WithOne("EmploymentDetails")
                        .HasForeignKey("ApiHrm.Domains.Entities.EmploymentDetails", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.Exit", b =>
                {
                    b.HasOne("ApiHrm.Domains.Entities.Employee", "Employee")
                        .WithMany("Exits")
                        .HasForeignKey("Employee_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.GovernmentId", b =>
                {
                    b.HasOne("ApiHrm.Domains.Entities.Employee", "Employee")
                        .WithOne("GovernmentId")
                        .HasForeignKey("ApiHrm.Domains.Entities.GovernmentId", "Employee_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.LeaveBalance", b =>
                {
                    b.HasOne("ApiHrm.Domains.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("Employee_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiHrm.Domains.Entities.LeaveType", "LeaveType")
                        .WithMany("LeaveBalances")
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.LeaveRequest", b =>
                {
                    b.HasOne("ApiHrm.Domains.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("Employee_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiHrm.Domains.Entities.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.MissingLog", b =>
                {
                    b.HasOne("ApiHrm.Domains.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("Employee_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.PayoutSummary", b =>
                {
                    b.HasOne("ApiHrm.Domains.Entities.PayrollRun", "PayrollRun")
                        .WithMany("PayoutSummaries")
                        .HasForeignKey("PayrollRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PayrollRun");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.Payslip", b =>
                {
                    b.HasOne("ApiHrm.Domains.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("Employee_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiHrm.Domains.Entities.PayrollRun", "PayrollRun")
                        .WithMany("Payslips")
                        .HasForeignKey("Payroll_Run_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("PayrollRun");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.Applicant", b =>
                {
                    b.Navigation("Checklists");

                    b.Navigation("Documents");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.Employee", b =>
                {
                    b.Navigation("CompanyProperty")
                        .IsRequired();

                    b.Navigation("ContactInformation")
                        .IsRequired();

                    b.Navigation("DocumentStatuses");

                    b.Navigation("Documents");

                    b.Navigation("EmergencyContacts");

                    b.Navigation("EmployeeDocuments");

                    b.Navigation("EmploymentDetails")
                        .IsRequired();

                    b.Navigation("Exits");

                    b.Navigation("GovernmentId")
                        .IsRequired();
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.LeaveType", b =>
                {
                    b.Navigation("LeaveBalances");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.PayrollRun", b =>
                {
                    b.Navigation("BonusIncentives");

                    b.Navigation("EmployeePayrollRecords");

                    b.Navigation("PayoutSummaries");

                    b.Navigation("Payslips");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.Role", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.ShiftDefinition", b =>
                {
                    b.Navigation("EmployeeShifts");
                });
#pragma warning restore 612, 618
        }
    }
}
