// <auto-generated />
using System;
using ApiHrm.Infrastructures.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace api_hrm.Migrations
{
    [DbContext(typeof(hrmAppDbContext))]
    [Migration("20260604113027_InitialHrmsSetup")]
    partial class InitialHrmsSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApiHrm.Domains.Entities.Applicant", b =>
                {
                    b.Property<int>("Applicant_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Applicant_ID"));

                    b.Property<DateTime>("Application_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Contact_Details")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Payment_Method")
                        .HasColumnType("text");

                    b.Property<string>("Resume_URL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Applicant_ID");

                    b.ToTable("r_Applicant_Records", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.Checklist", b =>
                {
                    b.Property<int>("Checklist_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Checklist_ID"));

                    b.Property<int>("Applicant_ID")
                        .HasColumnType("integer");

                    b.Property<bool>("Has_Medical")
                        .HasColumnType("boolean");

                    b.Property<bool>("Has_NBI")
                        .HasColumnType("boolean");

                    b.Property<bool>("Has_Xray")
                        .HasColumnType("boolean");

                    b.Property<bool>("has_PAGIBIG")
                        .HasColumnType("boolean");

                    b.Property<bool>("has_PhilHealth")
                        .HasColumnType("boolean");

                    b.Property<bool>("has_SSS")
                        .HasColumnType("boolean");

                    b.Property<bool>("has_TIN")
                        .HasColumnType("boolean");

                    b.HasKey("Checklist_ID");

                    b.HasIndex("Applicant_ID");

                    b.ToTable("r_Checklist", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.Document", b =>
                {
                    b.Property<int>("Document_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Document_ID"));

                    b.Property<int?>("Applicant_ID")
                        .HasColumnType("integer");

                    b.Property<string>("Doc_Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Employee_ID")
                        .HasColumnType("integer");

                    b.Property<string>("file_URL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("upload_date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Document_ID");

                    b.HasIndex("Applicant_ID");

                    b.HasIndex("Employee_ID");

                    b.ToTable("r_Document", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.Employee", b =>
                {
                    b.Property<int>("Employee_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Employee_Id"));

                    b.Property<string>("Contact_Details")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("Hire_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Payment_Method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role_ID")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Employee_Id");

                    b.HasIndex("Role_ID");

                    b.ToTable("r_Employee_Record", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.EmployeeHistory", b =>
                {
                    b.Property<int>("History_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("History_ID"));

                    b.Property<string>("Action_Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("Changed_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Changed_By")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Employee_ID")
                        .HasColumnType("integer");

                    b.Property<string>("New_Value")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Old_Value")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("History_ID");

                    b.HasIndex("Employee_ID");

                    b.ToTable("r_Employee_History", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.Exit", b =>
                {
                    b.Property<int>("Exit_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Exit_ID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Employee_ID")
                        .HasColumnType("integer");

                    b.Property<string>("Interview_Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Interviewed_By")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason_For_Leaving")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Exit_ID");

                    b.HasIndex("Employee_ID");

                    b.ToTable("r_Exit_Interviews", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.LeaveBalance", b =>
                {
                    b.Property<int>("Balance_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Balance_ID"));

                    b.Property<int>("Allocated_Days")
                        .HasColumnType("integer");

                    b.Property<int>("Employee_ID")
                        .HasColumnType("integer");

                    b.Property<int>("Leave_Code_ID")
                        .HasColumnType("integer");

                    b.Property<int>("Pending_Days")
                        .HasColumnType("integer");

                    b.Property<int>("Used_Days")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Balance_ID");

                    b.HasIndex("Employee_ID");

                    b.HasIndex("Leave_Code_ID");

                    b.ToTable("r_Leave_Balance", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.LeaveCode", b =>
                {
                    b.Property<int>("Leave_Code_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Leave_Code_ID"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Leave_Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Leave_Code_ID");

                    b.ToTable("r_Leave_Code", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.Role", b =>
                {
                    b.Property<int>("Role_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Role_ID"));

                    b.Property<string>("Role_Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Role_ID");

                    b.ToTable("r_Role", "public");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.Checklist", b =>
                {
                    b.HasOne("ApiHrm.Domains.Entities.Applicant", "Applicant")
                        .WithMany("Checklists")
                        .HasForeignKey("Applicant_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.Document", b =>
                {
                    b.HasOne("ApiHrm.Domains.Entities.Applicant", "applicant")
                        .WithMany("Documents")
                        .HasForeignKey("Applicant_ID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ApiHrm.Domains.Entities.Employee", "employee")
                        .WithMany("Documents")
                        .HasForeignKey("Employee_ID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("applicant");

                    b.Navigation("employee");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.Employee", b =>
                {
                    b.HasOne("ApiHrm.Domains.Entities.Role", "role")
                        .WithMany("Employees")
                        .HasForeignKey("Role_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("role");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.EmployeeHistory", b =>
                {
                    b.HasOne("ApiHrm.Domains.Entities.Employee", "Employee")
                        .WithMany("EmployeeHistories")
                        .HasForeignKey("Employee_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.Exit", b =>
                {
                    b.HasOne("ApiHrm.Domains.Entities.Employee", "Employee")
                        .WithMany("Exits")
                        .HasForeignKey("Employee_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.LeaveBalance", b =>
                {
                    b.HasOne("ApiHrm.Domains.Entities.Employee", "Employee")
                        .WithMany("LeaveBalances")
                        .HasForeignKey("Employee_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiHrm.Domains.Entities.LeaveCode", "LeaveCode")
                        .WithMany("LeaveBalances")
                        .HasForeignKey("Leave_Code_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("LeaveCode");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.Applicant", b =>
                {
                    b.Navigation("Checklists");

                    b.Navigation("Documents");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.Employee", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("EmployeeHistories");

                    b.Navigation("Exits");

                    b.Navigation("LeaveBalances");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.LeaveCode", b =>
                {
                    b.Navigation("LeaveBalances");
                });

            modelBuilder.Entity("ApiHrm.Domains.Entities.Role", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
